; Для компиляции скопируйте secrets.ini.template в secrets.ini файл

; Если у вас в Windows имя пользователя содержит кириллицу, измените home_dir
; [platformio]
; home_dir = C:\platformio

[platformio]
src_dir = src
default_envs = esp32s2
;extra_configs = secrets.ini  

[env]
firmware_version = "\"1.1.1\""

[libraries]
arduinojson = ArduinoJson@7.3.1
pubsubclient = PubSubClient@2.8
espasyncwebserver_124 = https://github.com/me-no-dev/ESPAsyncWebServer.git
                              
[env:esp32s2]
extra_scripts = post:post_compile.py

platform = https://github.com/Jason2866/platform-espressif32.git#24b67f905a
#Arduino/IDF5

framework = espidf, arduino
board = esp32-s2-saola-1

;upload_port=/dev/cu.usbmodem______1
upload_port=/dev/cu.usbmodem01
upload_speed = 921800

board_build.flash_mode = qio
board_build.filesystem = littlefs
board_build.partitions = partitions.csv

monitor_speed = 115200
monitor_filters = log2file, default

lib_ldf_mode = chain+
lib_archive = no

lib_deps =
  ${libraries.pubsubclient}
  ${libraries.arduinojson}
  ${libraries.espasyncwebserver_124}
lib_ignore =
  AsyncTCP_RP2040W

build_flags = 
  -DLOGLEVEL=2 ;если нужно логирование
  -DFIRMWARE_VERSION=${this.firmware_version}
  -DCONFIG_TINYUSB_ENABLED=1
  -DCONFIG_TINYUSB_CDC_ENABLED=1
  -DCONFIG_USB_ENABLED=1
  -DCONFIG_USB_CDC_ENABLED=1
  -DCONFIG_TINYUSB_CDC_RX_BUFSIZE=512
  -DCFG_TUSB_MCU=OPT_MCU_ESP32S2
  -DCFG_TUSB_OS_INC_PATH=freertos/
  -DARDUINO_USB_CDC_ON_BOOT=1
  -DARDUINO_USB_MODE=0
  -DCONFIG_AUTOSTART_ARDUINO=1
  -I ./src/usb
  -I ./managed_components/espressif__tinyusb/src


;

; Travis-CI
; platformio ci --project-conf=./platformio.ini -v .

; ========================================
; ESPTOOL Полезные команды python пакета esptool
; ========================================
;
; Загрузить прошивку
; -------------------
; Две команды - прошивка и файловая система
;
; platformio run --target upload --environment esp32s2 
; platformio run --target uploadfs --environment esp32s2
;
;
; Очистить память ESP
; -------------------
; python -m esptool --port /dev/cu.usbmodem01 --baud 921800 erase_flash
;
; Записать скомпилированную прошивку 
; -------------------
; python -m esptool --chip esp32s2 --port /dev/cu.usbmodem01 --baud 921800 --before default_reset --after hard_reset write_flash -z --flash_mode dio --flash_freq 80m --flash_size detect 0x1000 bootloader.bin 0x8000 partitions.bin 0x9000 ota_data_initial.bin 0x100000 firmware.bin 0x280000 littlefs.bin
;
; 0x1000 bootloader.bin 
; 0x8000 partitions.bin 
; 0x9000 ota_data_initial.bin 
; 0x100000 firmware.bin 
; 0x280000 littlefs.bin
; Просмотр стэка при падении прошивки
; -------------------
; 
; /waterius/ESP8266/.pio/build/esp32s2/firmware.elf


;
; cp .pio/build/esp32s2/firmware.elf ./../esp32s2-1.0.1.elf
; cp .pio/build/esp32s2/firmware.bin ./../esp32s2-1.0.1.bin
; cp .pio/build/esp32s2/littlefs.bin ./../esp32s2-1.0.1-fs.bin

